### ISSUE TITLE
index.js 제작 - 기초공사

### ISSUE THREAD

**Issue by KwakYounHo** [kongukjae/KDT-2-Project-A-5#3]
3. 그 html에 들어가는 js(데이터 요청) - 달재

**Comment by ParkDalJae** [comment]
server-rugin 브랜치 병합 완료.
데이터 출력 js 로직 작성

**Comment by ParkDalJae** [comment]
#7 작업내용 병합완료
issues/issue3/temp/pdj-test.js파일 내 xrl 방식 데이터 불러오기 로직 작성. 
src/views/js에는 적용 X
