### ISSUE TITLE
리액트 쿠키 연구

### ISSUE THREAD

**Issue by JangRuBin2** [kongukjae/KDT-2-Project-A-5#35]
리액트에서 로그인 후 유저 데이터를 활용하기 위해 쿠키 활용법에 대해 찾아보시면 됩니다

**Comment by KwonYeJun** [comment]
루빈씨와 같이 쿠키 연구 하였던거 mergTest브랜치에 병합 되어 이슈 닫습니다.

**Comment by KwonYeJun** [comment]
루빈씨와 같이 쿠키 연구 하였던거 mergTest브랜치에 병합 되어 이슈 닫습니다.
